server.port: 8080

saludo.pordefecto: "No hay entorno disponible"
   
spring.profiles.active: 
#-  "prod"
-  "dev"

spring:
  datasource:
    url: jdbc:h2:mem:mydb
#    url: jdbc:h2:file:/data/users
    username: root
    password: admin
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    hibernate: 
       ddl-auto: validate
       
    